# Execution Tutorial - Part 1

This tutorial covers the basics of executing a quantum program using Classiq directly through the Python SDK. It is also possible to use the [Classiq Platform](https://platform.classiq.io) to execute quantum algorithms.

For this, we will start by synthesizing the following example from the [synthesis tutorial](https://docs.classiq.io/latest/explore/tutorials/basic_tutorials/the_classiq_tutorial/synthesis_tutorial/):

## Example 1: Sampling Arithmetics and changing number of shots

In [1]:
from classiq import *


@qfunc
def main(x: Output[QNum[3]], y: Output[QNum]) -> None:
    allocate(x)
    hadamard_transform(x)
    y |= x**2 + 1


qprog = synthesize(main)
show(qprog)

Quantum program link: https://platform.classiq.io/circuit/3D5YX2Tk4w8uccjLqI6eDtSwgZv

This quantum program evaluates the function $y(x) = x^2 + 1$, for all integers $x \in [0,7]$. To execute a quantum program and sample the states, use `sample`:

In [2]:
results = sample(qprog)

Submitting job to simulator
Job: https://platform.classiq.io/jobs/df59aaa6-c03d-4401-8909-f3fc091fbe27

The output from `sample` is a dataframe with information regarding execution:

In [3]:
results

   x   y  counts  probability  bitstring
0  2   5     286     0.139648  000101010
1  5  26     282     0.137695  011010101
2  1   2     266     0.129883  000010001
3  6  37     258     0.125977  100101110
4  4  17     246     0.120117  010001100
5  7  50     246     0.120117  110010111
6  3  10     237     0.115723  001010011
7  0   1     227     0.110840  000001000

The information displayed in the dataframe is:

* `counts` shows the number of times each state was measured.
* `bitstring` is the bitstring that represents each state measured.
* `x` and `y` are the numerical representation of the states associated with the measurement.
* `probability` is the probability associated with each measured state.

By default, the number of executions of the quantum program is $2048$. This quantity, called the number of shots, can be modified inside `sample`. For instance, if we want to execute the same circuit with $10{,}000$ shots:

In [5]:
results_more_shots = sample(qprog, num_shots=10000)

Submitting job to simulator
Job: https://platform.classiq.io/jobs/aa0f5426-da35-4086-99fe-b1e6904fb579

The number of counts for each state will grow proportionally with the number of shots:

In [7]:
results_more_shots

   x   y  counts  probability  bitstring
0  1   2    1312       0.1312  000010001
1  2   5    1270       0.1270  000101010
2  4  17    1257       0.1257  010001100
3  5  26    1245       0.1245  011010101
4  7  50    1237       0.1237  110010111
5  3  10    1232       0.1232  001010011
6  0   1    1225       0.1225  000001000
7  6  37    1222       0.1222  100101110

## Example 2: GHZ States and noise

Many simulators provide noise models that approximate the behavior of real quantum hardware. In this example, we create a GHZ state using the Classiq simulator while emulating the noise profile of IBM Pittsburgh, an IBM backend available through Classiq.

We begin by defining the model for the GHZ state:

In [1]:
from classiq import *


@qfunc
def main(x: Output[QArray[QBit, 3]]):
    allocate(x)
    H(x[0])
    CX(x[0], x[1])
    CX(x[1], x[2])


qprog = synthesize(main)

Next, we configure the simulator to use the noise model associated with the IBM Pittsburgh backend. This is done by passing a `noise_model` entry through the `config` argument:

In [2]:
cfg = {"noise_model": "ibm_pittsburgh"}
res = sample(qprog, backend="simulator", config=cfg)
res

Submitting job to simulator
Job: https://platform.classiq.io/jobs/e5ddc36b-7982-49e6-ba15-de607cf24b59

           x  counts  probability bitstring
0  [1, 1, 1]    1027     0.501465       111
1  [0, 0, 0]     992     0.484375       000
2  [0, 0, 1]       7     0.003418       100
3  [1, 0, 1]       7     0.003418       101
4  [1, 0, 0]       5     0.002441       001
5  [1, 1, 0]       4     0.001953       011
6  [0, 1, 1]       4     0.001953       110
7  [0, 1, 0]       2     0.000977       010

For an ideal, noiseless GHZ state, the only expected measurement outcomes are `[0, 0, 0]` and `[1, 1, 1]`, each occurring with approximately equal probability. All other basis states should have zero probability.

Here, because the simulation includes a realistic noise model, a small fraction of the measurements appears in other states. The dominant outcomes are still `[0, 0, 0]` and `[1, 1, 1]`, but the presence of low-probability additional bitstrings reflects the effect of hardware noise on the quantum program execution.

## State vector simulation

A state vector simulator returns the amplitudes of the quantum states produced by a quantum program. Unlike sampling, which estimates output probabilities from repeated measurements, state vector simulation gives direct access to the simulated quantum state.

On real quantum hardware, these amplitudes are not directly observable. Reconstructing them requires quantum state tomography, which involves measuring the system in different bases to infer the output state.

In this example, we calculate the state vector of the quantum program using `calculate_state_vector`:

In [3]:
res_sv = calculate_state_vector(qprog)
res_sv

Submitting job to simulator
Job: https://platform.classiq.io/jobs/17914bca-064b-44bb-872f-5c7334cb3828

           x           amplitude magnitude  phase  probability bitstring
0  [0, 0, 0]  0.707107+0.000000j      0.71  0.00π          0.5       000
1  [1, 1, 1]  0.707107+0.000000j      0.71  0.00π          0.5       111

The information displayed in the dataframe is:

* `amplitude` is the complex amplitude associated with each basis state.
* `magnitude` is the absolute value of the amplitude.
* `phase` is the phase of the amplitude.
* `probability` is the probability of measuring the corresponding state.
* `bitstring` is the bitstring representation of the basis state.
* `x` is the value of the quantum array. It is displayed as a list of 0s and 1s, with each entry corresponding to one qubit in the array.

In this case, the output corresponds to an ideal GHZ state. The only states with nonzero probability are `[0, 0, 0]` and `[1, 1, 1]`, each with probability 0.5 and amplitude approximately $1/\sqrt{2}$.

## Backend selection

The backend of an execution is the hardware or simulator where the quantum program is executed. To select a specific backend, it is necessary to know its correct name and provider. To do so, run `get_backend_details()` for a concise list of available backends.

In [5]:
backend_list = get_backend_details()
backend_list.head()

,provider,backend,type,num_qubits,is_available,pending_jobs,queue_time
0,classiq,nvidia_simulator,simulator,29,True,NaN,NaT
1,classiq,simulator,simulator,28,True,NaN,NaT
2,classiq,simulator_density_matrix,simulator,28,True,NaN,NaT
3,classiq,simulator_matrix_product_state,simulator,28,True,NaN,NaT
4,alice&bob,LOGICAL_EARLY,simulator,15,True,NaN,NaT

Now, to define a backend, set the backend name following the rule `"provider/backend"` under the execution function used. For example, you can use the [Nvidia simulator](https://docs.classiq.io/user-guide/execution/cloud-providers/classiq-backends#nvidia-simulator-usage) to realize a state vector simulation of the GHZ state, or the [MPS simulator](https://docs.classiq.io/user-guide/execution/cloud-providers/classiq-backends#supported-backends) to sample over the same state:

In [ ]:
nvidia_backend = "classiq/nvidia_simulator"
MPS_backend = "classiq/simulator_matrix_product_state"

res_nvidia = calculate_state_vector(qprog, backend=nvidia_backend)
res_MPS = sample(qprog, MPS_backend)

In [7]:
res_nvidia

           x           amplitude magnitude  phase  probability bitstring
0  [0, 0, 0]  0.707107+0.000000j      0.71  0.00π          0.5       000
1  [1, 1, 1]  0.707107+0.000000j      0.71  0.00π          0.5       111

In [8]:
res_MPS

           x  counts  probability bitstring
0  [0, 0, 0]    1027     0.501465       000
1  [1, 1, 1]    1021     0.498535       111